{{- if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.fullname" $ }}-ingress
spec:
  rules:
  - host: {{ $.Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "common.fullname" $ }}-service
            port:
              number: 8000
        path: /
        pathType: Prefix
{{- end }}
