---
image:
  repository: lib42/jackett
  tag: "latest"
  pullPolicy: Always

env:
  - name: TZ
    value: UTC

ingress:
  main:
    enabled: false
    #annotations:
    #  cert-manager.io/cluster-issuer: "vault-issuer"
    #  traefik.ingress.kubernetes.io/router.tls: 'true'
    #  nginx.ingress.kubernetes.io/proxy-body-size: 50m
    #hosts:
    #  - host: jacket.local
    #    paths:
    #      - path: /
    #        pathType: Prefix
    #tls:
    #  - secretName: jacket-tls
    #    hosts:
    #       - jacket.local

service:
  main:
    enabled: true
    ports:
      http:
        port: 9117

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 100M

podSecurityContext:
  runAsUser: 1420
  runAsGroup: 1420
  fsGroup: 1420
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  runAsNonRoot: true
  privileged: false
  # FIXME: Jackett crashes if rootfs is read only
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
